
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import AppModals from "@/components/AppModals/AppModals";
import { Metadata } from "next";
import { Suspense } from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import { eventType } from "@/types";
import { fetchGoogleCalendarEvents } from "@/lib/actions/events";
import { CalendarEventsProvider } from "@/context/CalendarEventsContext";

// Product Sans is not available via next/font/google.
// You must self-host it or use a CDN (see note below).

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    let events: eventType[] = [];
    let error: string | null = null;
    let initialLoading = true;

    try {
        events = await fetchGoogleCalendarEvents();
        initialLoading = false;
        console.log("Fetched events on server:", events);
    } catch (e) {
        console.error("Server-side fetching failed:", e);
        error = e instanceof Error
            ? e.message
            : "An unknown error occurred while fetching initial data.";
        initialLoading = false;
    }

    return (
        <html lang="en">
            <body
                className={`antialiased`}
            >
                <ClerkProvider>
                    <CalendarEventsProvider initialEvents={events}>
                        {children}
                        <Suspense fallback={null}>
                            <AppModals />
                        </Suspense>
                    </CalendarEventsProvider>

                </ClerkProvider>

                <ToastContainer />
            </body>
        </html>
    );
}