
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import AppModals from "@/components/AppModals/AppModals";
import { Metadata } from "next";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


// Product Sans is not available via next/font/google.
// You must self-host it or use a CDN (see note below).

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased`}
            >
                <ClerkProvider>
                    {children}
                </ClerkProvider>
                <AppModals />
                <ToastContainer />
            </body>
        </html>
    );
}